"""empty message

Revision ID: bb64ad60109d
Revises: b70344e1366d
Create Date: 2021-10-28 12:03:39.714787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb64ad60109d'
down_revision = 'b70344e1366d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
