"""empty message

Revision ID: ded375d1a716
Revises: 
Create Date: 2021-12-13 06:34:41.813373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ded375d1a716'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medicine',
    sa.Column('id_medicine', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=True),
    sa.Column('manufacturer', sa.String(length=45), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('in_stock', sa.Boolean(), nullable=True),
    sa.Column('demand', sa.Boolean(), nullable=True),
    sa.Column('in_stock_number', sa.Integer(), nullable=True),
    sa.Column('demand_number', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id_medicine')
    )
    op.create_table('user',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('firstName', sa.String(length=45), nullable=True),
    sa.Column('lastName', sa.String(length=45), nullable=True),
    sa.Column('login', sa.String(length=45), nullable=True),
    sa.Column('password', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id_user')
    )
    op.create_table('order',
    sa.Column('id_order', sa.Integer(), nullable=False),
    sa.Column('id_medicine', sa.Integer(), nullable=True),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('shipDate', sa.DateTime(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_medicine'], ['medicine.id_medicine'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id_user'], ),
    sa.PrimaryKeyConstraint('id_order')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order')
    op.drop_table('user')
    op.drop_table('medicine')
    # ### end Alembic commands ###
